export default {
    CHANGE_MENU_ITEM: 'CHANGE_MENU_ITEM',
    CHANGE_THEME: 'CHANGE_THEME',
    CHANGE_VIEW: 'CHANGE_VIEW',
    TASK_ADDED: 'TASK_ADDED',
    TASK_REMOVED: 'TASK_REMOVED',
    TASK_UPDATED: 'TASK_UPDATED'
}